from Tests.Annotation import TestAnnotationMethods
from Tests.Chore import TestChoreMethods
from Tests.Cube import TestCubeMethods
from Tests.Dimension import TestDimensionMethods
from Tests.Hierarchy import TestHierarchyMethods
from Tests.Process import TestProcessMethods
from Tests.Subset import TestSubsetMethods
from Tests.Security import TestUserMethods
from Tests.View import TestViewMethods
