name: Build and Deploy Docs

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.?[0-9]*" # Triggered by versions tags e.g. 2.0 or 2.0.1
  workflow_dispatch: # Manually triggered
jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements-docs.txt
          pip install .

      - name: Configure Git (for mike commits)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages branch (if exists)
        run: git fetch origin gh-pages:gh-pages || echo "gh-pages does not exist yet"  

      - name: Extract versions.json
        run: |
          git show origin/gh-pages:versions.json > versions.json          

      - name: Filter versions
        run: |
          python scripts/filter_versions.py versions.json > version_filter_output.json

      - name: Deploy visible versions
        run: |
          for v in $(jq -r '.visible[]' version_filter_output.json); do
            mike deploy --push $v
          done
    
      - name: Deploy hidden versions
        run: |
          for v in $(jq -r '.hidden[]' version_filter_output.json); do
            mike deploy --push --hidden $v
          done

      - name: Set default version
        run: |
          latest=$(jq -r '.visible[0]' version_filter_output.json)
          mike set-default --push $latest    
 

